# Generated by Django 5.2.9 on 2025-12-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('antiguedad_meses', models.IntegerField()),
                ('frecuencia_uso', models.IntegerField(help_text='Cantidad de usos del servicio por mes')),
                ('reclamos', models.IntegerField(default=0)),
                ('pagos_atrasados', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
