# Generated by Django 5.2.9 on 2025-12-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_empresa_cliente_empresa_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='churn_probabilidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='churn_riesgo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
